#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t tesla"
$L " _____                _              ___    ____   ";
$L "|_   _|   ___   ___  | |   __ _     / _ \  / ___|  ";
$L "  | |    / _ \ / __| | |  / _` |   | | | | \___ \  ";
$L "  | |   |  __/ \__ \ | | | (_| |   | |_| |  ___) | ";
$L "  |_|    \___| |___/ |_|  \__,_|    \___/  |____/  ";
$L "                                                   ";
$L "Welcome to Android `getprop ro.build.version.release` / TeslaOS-`getprop ro.tesla.version`";
